### ISSUE TITLE
Please add permisisons :)

### ISSUE THREAD

**Issue by vacer25** [JadedDragoon/Player-Time-Weather#1]
Hi, this is an awesome plugin!

One thing I'd like to see added is permission nodes for each of the commands.
This would make it possible to use on servers with different worlds, for example giving access in a creative world, but limiting/denying access in a survival world.

If you could add a build guide I could add this feature myself and submit a PR (I can't seem figure out how to build it in either Eclipse or IntelliJ).

**Comment by JadedDragoon** [comment]
SpigotMC.com actually already provides a build guide for eclipse [here](https://www.spigotmc.org/wiki/creating-a-blank-spigot-plugin-in-eclipse/?noRedirect=1) and IntelliJ [here](https://www.spigotmc.org/wiki/creating-a-blank-spigot-plugin-in-intellijidea/). I followed the eclipse guide myself when setting this up.

You make a valid point about multi-world servers. I would actually need to do a bit of testing to see what happens when a user with time/weather locked travels to a different world and whether I need to listen for that and take steps to resync the user's time/weather. EDIT: Yes, I do.

One issue is that the introduction of permissions would be a breaking change. I'd likely require a config file to enable permissions for the plugin so that existing configurations would not be disrupted. And I really want to keep this dead-simple in the default configuration. I'll look into the available options.

**Comment by vacer25** [comment]
Thanks for those links!

When adding permissions, would it be possible to define that everything is granted to everyone by default? That way it will not be a breaking change as all permissions are effectively granted for everyone as of now.

**Comment by JadedDragoon** [comment]
I'm considering doing exactly that. It depends on how exactly such will behave in a few different scenarios. I'll update when I have a firmer answer.

**Comment by JadedDragoon** [comment]
Okay, I've implemented permissions in the [latest beta release](https://github.com/JadedDragoon/Player-Time-Weather/releases/tag/0.5.0_b1).

It's marked beta because it needs testing with additional permissions plugins and has known issues. I tested it with LuckPerms and bPermissions. LuckPerms worked flawlessly. bPermissions had issues with global negation of default permissions (see release notes). Feel free to give it a try if you like. If you're using a different permissions plugin I'd appreciate a report back on how it works.

**Comment by vacer25** [comment]
Thank you for the quick response! I'm using LuckPerms, but I'll confirm that everything works.

**Comment by vacer25** [comment]
The permissions seem to work just fine, thank you for the added feature!

However the synchronization notification chat messages appear every time when switching worlds, even if both time and weather were in sync before switching. It would be great if those notification chat messages only appeared if a player-set time/weather was active before switching worlds.

**Comment by JadedDragoon** [comment]
Glad to hear it's working.

It only does the synchronization messages between worlds now because of the existing structure of subcommands in the code. Which I didn't change for this beta release. There will be no synchronization notifications when traveling between worlds in the next release.

I'll close this issue once I've finished testing with a few more popular permissions plugins and made another release. Just to make sure there are no other quirks I need to account for.
